import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import { Toaster } from "react-hot-toast";
import AdminDashboard from "./admin-dashboard/pages";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAdmin: boolean = false;

  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" reverseOrder={false} />
        {isAdmin ? (
          <AdminDashboard />
        ) : (
          <>
            <Navbar />
            <div>{children}</div>
          </>
        )}
      </body>
    </html>
  );
}
